version: '3.7'
services:
  database-mysql:
    container_name: database-mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'mysqlDB'
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password


    volumes:
      - database-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    restart: always


### Application

  app-service:
    container_name: app-service
    image: khalilmissaoui/client-tech-gestion:data-layer.v1
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - database-mysql


volumes:
  database-mysql:
    driver: local
