version: '3.7'
services:
  database-postgres:
    container_name: database-postgres
    image: postgres
    environment:
      POSTGRES_DB: database-postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - database-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: -p 5432
    expose:
      - "5432"
    restart: always




volumes:
  database-postgres:
    driver: local
